shop/app_settings/urls.py
"""Модуль содержит URL-адреса для работы с настройками сайта."""
from django.urls import path

from app_settings import views

app_name = "app_settings"
urlpatterns = [
    path("admin/dashboard/", views.AdminDashBoardView.as_view(), name="dashboard"),
    path("settings/", views.SettingsView.as_view(), name="settings"),
    path("edit/<int:pk>/", views.SettingsUpdatedView.as_view(), name="settings_edit"),
    path("customer/list/", views.CustomerListView.as_view(), name="customer_list"),
    path(
        "customer/<int:pk>/update/",
        views.CustomerDeleteView.as_view(),
        name="customer_update_status",
    ),
    path("seller/list/", views.SellerListView.as_view(), name="seller_list"),
    path(
        "seller/<int:pk>/update/",
        views.SellerDeleteView.as_view(),
        name="seller_update_status",
    ),
    path("store/list/", views.StoreListView.as_view(), name="store_list"),
    path("product/list/", views.ProductListView.as_view(), name="product_list"),
    path("comments/list/", views.CommentListView.as_view(), name="comments_list"),
    path(
        "comment/<int:pk>/detail/", views.CommentDetail.as_view(), name="comment_detail"
    ),
    path(
        "comment/<int:pk>/update/",
        views.CommentModerate.as_view(),
        name="comment_update",
    ),
    path(
        "comment/<int:pk>/delete/", views.CommentDelete.as_view(), name="comment_delete"
    ),
    path("category/list/", views.CategoryListView.as_view(), name="category_list"),
    path(
        "category/create/", views.CategoryCreateView.as_view(), name="create_category"
    ),
    path(
        "category/<int:pk>/edit/",
        views.CategoryUpdateView.as_view(),
        name="category_edit",
    ),
    path(
        "category/<int:pk>/delete/",
        views.CategoryDeleteView.as_view(),
        name="category_delete",
    ),
    path("tag/list/", views.TagListView.as_view(), name="tag_list"),
    path("tag/create/", views.TagCreateView.as_view(), name="tag_create"),
    path("tag/<int:pk>/edit/", views.TagUpdateView.as_view(), name="tag_edit"),
    path("tag/<int:pk>/delete/", views.TagDeleteView.as_view(), name="tag_delete"),
    path(
        "feature/list/<int:pk>/", views.FeatureListView.as_view(), name="feature_list"
    ),
    path(
        "feature/create/<int:pk>/",
        views.FeatureCreateView.as_view(),
        name="feature_create",
    ),
    path(
        "feature/edit/<int:category_id>/feature/<int:pk>/",
        views.FeatureUpdateView.as_view(),
        name="feature_edit",
    ),
    path(
        "feature/delete/<int:category_id>/feature/<int:pk>/",
        views.FeatureDeleteView.as_view(),
        name="feature_delete",
    ),
    path(
        "feature/value/<int:pk>/create/",
        views.ValueCreateView.as_view(),
        name="value_create",
    ),
    path(
        "feature/delete/<int:category_id>/value/<int:pk>/",
        views.ValueDeleteView.as_view(),
        name="value_delete",
    ),
    path("order/list/", views.OrderListView.as_view(), name="admin_order_list"),
    path(
        "order/<int:pk>/detail/",
        views.OrderDetailView.as_view(),
        name="admin_order_detail",
    ),
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop import views as shop_views


handler403 = "shop.views.my_permission_denied"
handler404 = "shop.views.my_page_not_found"
handler500 = "shop.views.my_server_error"

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("", shop_views.MainPage.as_view(), name="main"),
    path(
        "accounts/",
        include(("app_user.urls", "app_user"), namespace="app_user"),
    ),
    path(
        "cart/", include(("app_cart.urls", "app_cart"), namespace="app_cart")
    ),
    path(
        "compare/",
        include(("app_compare.urls", "app_compare"), namespace="app_compare"),
    ),
    path(
        "favorite/",
        include(
            ("app_favorite.urls", "app_favorite"), namespace="app_favorite"
        ),
    ),
    path(
        "order/",
        include(("app_order.urls", "app_order"), namespace="app_order"),
    ),
    path(
        "store/",
        include(("app_store.urls", "app_store"), namespace="app_store"),
    ),
    path(
        "item/", include(("app_item.urls", "app_item"), namespace="app_item")
    ),
    path(
        "invoice/",
        include(("app_invoice.urls", "app_invoice"), namespace="app_invoice"),
    ),
    path(
        "settings/",
        include(
            ("app_settings.urls", "app_settings"), namespace="app_settings"
        ),
    ),
    path("__debug__/", include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

shop/app_settings/views.py
"""
Модуль содержит классы-предстывления для работы с настроками сайта.

    классы-представления для работы с панели управления администратора:

    1. AdminDashBoardView - отображения панели администратора,
    2. SettingsView - отображения сновных настороек сайта,
    3. SettingsUpdatedView - редактирования сновных настороек сайта,

    классы-представления для работы с пользователями:

    4. CustomerListView - для списка покупателей,
    5. CustomerDeleteView - для (де)активации покупатель,
    6. SellerListView - для списока продавцов,
    7. SellerDeleteView - для (де)активации продавцов,
    8. StoreListView - для списока магазинов,
    9. ProductListView - для списка тоаров,

    классы-представления для работы с категориями:

    10. CategoryListView - для списка категорий,
    11. CategoryCreateView - для создания категории,
    12. CategoryUpdateView - для редактировании категории,
    13. CategoryDeleteView - для (де)активации каетгории,

    классы-представления для работы с тегами:

    14. TagListView - для списка тегов,
    15. TagCreateView - для создания тега,
    16. TagUpdateView - для редактировании тега,
    17. TagDeleteView - для (де)активации тега,

    классы-представления для работы с характеристиками:

    18. FeatureListView - для списка характеристик,
    19. FeatureCreateView - для создания характеристики,
    20. FeatureUpdateView - для редактировании характеристики,
    21. FeatureDeleteView - для (де)активации характеристики,
    22. ValueCreateView - для создания значения характеристики,

    классы-представления для работы с комментариями:

    23. CommentListView - для списка комментариев,
    24. CommentDetail - для одного комментария,
    25. CommentDelete - для удаления комментария,
    26. CommentModerate - для модерациия комментария,

    классы-представления для работы с заказами:

    27.OrderListView - для списка заказов,
    28.OrderDetailView - для одного заказа.
"""
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Sum, Count, Q
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse, Http404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

# models
from app_item import models as item_models
from app_settings import models as settings_modals
from app_order import models as order_models
from app_user import models as auth_modals
from app_store import models as store_modals

# forms
from app_settings import forms as admin_forms
from app_settings import forms as settings_form

# services
from app_item.services import comment_services
from app_order.services import order_services
from app_item.services import item_services
from app_store.services import store_services

# other
from utils.my_utils import AdminOnlyMixin, MixinPaginator


class AdminDashBoardView(AdminOnlyMixin, generic.TemplateView):
    """Класс-представление для отображения панели  администратора."""

    template_name = "app_settings/admin/dashboard.html"

    def get(self, request, *args, **kwargs):
        """Функция возвращает context-словарь с данными панели администратора."""
        context = self.get_context_data(**kwargs)
        context[
            "categories"
        ] = item_services.CategoryHandler.admin_category_count()
        context[
            "comments_count"
        ] = comment_services.CommentHandler.non_moderate_comments_amount()
        context["customer"] = auth_modals.Profile.objects.filter(
            user__groups__name="customer"
        ).count()
        context["items"] = item_services.ItemHandler.admin_item_count()
        context["orders"] = order_services.AdminOrderHAndler.orders_count()
        context["seller"] = auth_modals.Profile.objects.filter(
            user__groups__name="seller"
        ).count()
        context["stores"] = store_services.AdminStoreHandler.stores_count()
        context["tags"] = item_services.TagHandler.admin_tag_count()

        return self.render_to_response(context)


class SettingsView(AdminOnlyMixin, generic.TemplateView):
    """Класс-представление для отображения сновных настороек сайта."""

    template_name = "app_settings/admin/settings.html"


class SettingsUpdatedView(AdminOnlyMixin, generic.UpdateView):
    """Класс-представление для редактирования сновных настороек сайта."""

    model = settings_modals.SiteSettings
    template_name = "app_settings/admin/settings_edit.html"
    form_class = admin_forms.UpdateSettingsForm
    MESSAGE_SUCCESS = "Настройки обновлены"
    MESSAGE_ERROR = "Ошибка. Настройки не обновлены."

    def form_valid(self, form):
        """Функция валидации формы для реадактирования настроек."""
        form.save()
        messages.add_message(
            self.request, messages.SUCCESS, self.MESSAGE_SUCCESS
        )
        return redirect("app_settings:dashboard")

    def form_invalid(self, form):
        """Функция инвалидации формы для реадактирования настроек."""
        messages.add_message(
            self.request, messages.ERROR, self.MESSAGE_ERROR
        )
        return super().form_invalid(form)


class CustomerListView(AdminOnlyMixin, generic.ListView):
    """Класс-представление для списка покупателей."""

    model = auth_modals.User
    template_name = "app_settings/customer/customer_list.html"
    paginate_by = 4

    def get_queryset(self):
        """Функция возвращает queryset покупателей."""
        queryset = (
            auth_modals.User.objects.filter(groups__name="customer")
            .annotate(amount=Count("user_order"))
            .order_by("-amount")
        )
        return queryset

    def get(self, request, *args, **kwargs):
        """GET-функция для рендеренга списка покупателей."""
        object_list = self.get_queryset()
        if self.request.GET:
            if self.request.GET.get("search"):
                search = str(self.request.GET.get("search")).title()
                object_list = object_list.filter(
                    Q(first_name__startswith=search) |
                    Q(last_name__startswith=search)
                )
        object_list = MixinPaginator(
            object_list, self.request, self.paginate_by
        ).my_paginator()
        context = {
            "object_list": object_list
        }
        return render(self.request, self.template_name, context=context)


class CustomerDeleteView(AdminOnlyMixin, generic.UpdateView):
    """Класс-представление для блокировки/разблокировки покупатель."""

    model = auth_modals.User

    def get(self, request, *args, **kwargs):
        """GET-функция для блокировки/разблокировки покупатель."""
        customer_id = kwargs["pk"]
        try:
            customer = auth_modals.User.objects.get(id=customer_id)
            customer_name = customer.get_full_name()
            if customer.profile.is_active:
                customer.profile.is_active = False
                message = f"Покупатель {customer_name} разблокирован"
            else:
                customer.profile.is_active = True
                message = f"Покупатель {customer_name} заблокирован"
            customer.profile.save()
            messages.add_message(self.request, messages.WARNING, message)
            return redirect("app_settings:customer_list")
        except ObjectDoesNotExist:
            raise Http404("Такого покупателя не существует.")


class SellerListView(AdminOnlyMixin, generic.ListView):
    """Класс-представление для списока продавцов."""

    model = auth_modals.User
    template_name = "app_settings/seller/seller_list.html"
    paginate_by = 4

    def get_queryset(self):
        """Функция возвращает queryset продавцов."""
        queryset = auth_modals.User.objects.filter(groups__name="seller")
        return queryset

    def get(self, request, *args, **kwargs):
        """GET-функция для рендеренга списка покупателей."""
        object_list = self.get_queryset()
        if self.request.GET:
            if self.request.GET.get("search"):
                search = self.request.GET.get("search")
                object_list = object_list.filter(
                    Q(first_name__startswith=search) |
                    Q(last_name__startswith=search)
                )
        object_list = MixinPaginator(
            object_list, self.request, self.paginate_by
        ).my_paginator()
        context = {"object_list": object_list}
        return render(self.request, self.template_name, context=context)


class SellerDeleteView(AdminOnlyMixin, generic.UpdateView):
    """Класс-представление для блокировки/разблокировки продавеца."""

    model = auth_modals.User

    def get(self, request, *args, **kwargs):
        """GET-функция для блокировки/разблокировки продавеца."""
        try:
            seller = auth_modals.User.objects.get(id=kwargs["pk"])
            seller_name = seller.get_full_name()
            if seller.profile.is_active:
                seller.profile.is_active = False
                message = f"Продавец {seller_name} заблокирован"
            else:
                seller.profile.is_active = True
                message = f"Продавец {seller_name} разблокирован "
            seller.profile.save()
            messages.add_message(
                self.request, messages.WARNING, message
            )
            return redirect("app_settings:seller_list")
        except ObjectDoesNotExist:
            raise Http404("Такого продавца не существует")


class StoreListView(AdminOnlyMixin, generic.ListView):
    """Класс-представление для списка магазинов."""

    model = store_modals.Store
    template_name = "app_settings/store/store_list.html"
    paginate_by = 4
    queryset = store_modals.Store.objects.order_by("created")

    def get(self, request, *args, **kwargs):
        """GET-функция для рендеренга списка магазинов."""
        object_list = self.queryset
        if self.request.GET:

shop/app_settings/templates/app_settings/tag/tag_create.html
{% extends 'app_settings/admin/admin_index.html' %}
{% load static %}
{% load cache %}

{% block title %} Добавить тег {% endblock %}

{% block heard %} {% include 'search_string.html' %} {% endblock %}
{% block content %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">новый тег </h1>
                 {% block breadcrumbs %}

                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item">
                        <a href="{% url 'app_settings:tag_list' %}">список тегов </a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current">
                        <span>новый тег</span>
                    </li>
                </ul>
                {% endblock %}
            </div>
        </div>
    </div>
    {% include 'messages/message.html' %}
    <div class="Section">
        <div class="wrap">
            <div class="form Payment">
                <div class="Payment-card form-shadow">
                    <div class="form-group">
                        <form class="form" action="." method="post">
                            {% csrf_token %}
                            {% if form.errors.title %}
                                <div class="form-error">{{ form.errors.title }}
                                </div>
                            {% endif %}
                            <div class="form-group">
                                <input class="form-input" id="title" name="title" value="{{ object }}"/>
                            </div>
                            <div class="form-group">
                                <button class="btn btn_square btn_success btn_narrow" type="submit">
                                    сохранить
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/app_settings/templates/app_settings/tag/tag_edit.html
{% extends 'app_settings/admin/admin_index.html' %}
{% load static %}
{% load cache %}


{% block title %} Редактировать тег {% endblock %}

{% block heard %} {% include 'search_string.html' %} {% endblock %}
{% block content %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">Редактировать тег <b>{{ object.title }}</b></h1>
                 {% block breadcrumbs %}

                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item">
                        <a href="{% url 'app_settings:tag_list' %}">список тегов </a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current">
                        <span>редактировать тег</span>
                    </li>
                </ul>
                {% endblock %}
            </div>
        </div>
    </div>
    {% include 'messages/message.html' %}
    <div class="Section">
        <div class="wrap">
            <div class="form Payment">
                <div class="Payment-card form-shadow">
                    <div class="form-group">
                        <form class="form" action="." method="post">
                            {% csrf_token %}
                            {% if form.errors.title %}
                                <div class="form-error">{{ form.errors.title }}
                                </div>
                            {% endif %}
                            <div class="form-group">
                                <input class="form-input" id="title" name="title" value="{{ object }}"/>
                            </div>
                            <div class="form-group">
                                <button class="btn btn_square btn_success btn_narrow" type="submit">
                                    сохранить
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/app_settings/templates/app_settings/tag/tag_list.html
{% extends 'app_settings/admin/admin_index.html' %}%}
{% load static %}
{% load cache %}

{% block title %}Каталог{% endblock %}
{% block content %}

<div class="Middle Middle_top" xmlns="http://www.w3.org/1999/html">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">
                    {% if request.GET %}
                    поиск тегов по &#8195;<b class="primary-text">'{{ request.GET.search}}'</b>
                    {% else %}
                    теги
                    {% endif %}
                </h1>
                {% block breadcrumbs %}
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item">
                        <a href="{% url 'app_settings:dashboard' %}">главная старница </a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current">
                        <span>Список тегов</span>
                    </li>
                </ul>
                {% endblock %}
            </div>
        </div>
    </div>

    <!--    MESSAGE STRING  -->
    {% include 'messages/message.html' %}
    <!--    MESSAGE STRING  -->

    <div class="Section">
        <div class="wrap">
            <div class="Cart">
                <div class="Cart-product">
                    <div class="Cart-block Cart-block_row">
                        <a class="form-input btn btn_square btn_primary"
                           href="{% url 'app_settings:tag_create' %}">создать тег
                        </a>
                    </div>
                    <div class="Cart-block Cart-block_row">
                        <form class="Cart-block Cart-block_delete" method="get" action="{% url 'app_settings:tag_list' %}">
                            <div class="row ">
                                <div class="form-label">&#8195;</div>
                                <input class="form-input" name="search" value="{{ request.GET.search }}"
                                       placeholder="поиск тега по названию">
                                <div class="form-label">&#8195;</div>
                                <input class="form-input btn btn_square btn_success"
                                       type="submit" value="найти">
                                <div class="form-label">&#8195;</div>
                                <a class="form-input btn btn_square btn_dark"
                                   href="{% url 'app_settings:tag_list' %}">очистить
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="Cart">
                {% for object in object_list %}
                <div class="Cart-product">
                    <div class="Cart-block Cart-block_row" style="margin:0 20px">
                        <div class="Cart-block Cart-block_pict">
                        </div>
                        <div class="Cart-block Cart-block_info">
                            {% if object.is_active %}
                            <span class="Cart-title ">{{ object }}
                            </span>
                            {% else %}
                            <span class="Cart-title Cart-title-not_available">{{ object }}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="Cart-block Cart-block_row" style="margin:0 20px">

                        <!--  EDIT TAG -->
                        <div class="Cart-block Cart-block_seller">
                            {% if  not object.is_active %}
                            <div class="danger-text">в архиве</div>
                            {% else %}
                             <a class="Cart-delete" href="{% url 'app_settings:tag_edit' pk=object.pk %}">
                                <img src="/assets/img/icons/edit.png" width="32">
                            </a>
                            {% endif %}
                        </div>
                        <!-- EDIT TAG -->

                        <!--   REMOVE TAG    -->
                        <div class="Cart-block Cart-block_delete">
                             {% if object.is_active %}
                            <a class="Cart-delete" href="{% url 'app_settings:tag_delete'  pk=object.pk %}">
                                <img src="/assets/img/icons/card/delete.svg" alt="delete.svg"/>
                            </a>
                            {% else %}
                            <a class="Cart-delete" href="{% url 'app_settings:tag_delete'  pk=object.pk %}">
                                <img src="/assets/img/icons/update.svg" alt="delete.svg"/>
                            </a>
                            {% endif%}
                        </div>
                        <!--   REMOVE TAG   -->
                    </div>
                </div>
                {% empty %}
                <div class="form-group">
                    <img src="/media/default_images/not_found.png" width="100%">
                </div>
                {% endfor %}

            </div>
            <!--       PAGINATION         -->
            <div>{% include "pagination/pagination.html" %}</div>
            <!--       PAGINATION         -->
        </div>
    </div>
</div>

{% endblock %}