shop/app_item/urls.py
"""Модуль содержит URL-адреса для работы с каталогом товаров."""
from django.urls import path
from app_item import views

app_name = "app_item"


urlpatterns = [
    path(
        "list/best_seller",
        views.ItemBestSellerList.as_view(),
        name="item_best_seller",
    ),
    path("list/new", views.ItemNewList.as_view(), name="item_new"),
    path("list/for_you", views.ItemForYouList.as_view(), name="item_for_you"),
    path("list/search/", views.FilterListView.as_view(), name="search"),
    path("list/filter/", views.FilterListView.as_view(), name="filter"),
    path(
        "list/category/<slug:category>/",
        views.CategoryListView.as_view(),
        name="item_category",
    ),
    path("list/tag/<slug:tag>/", views.TagListView.as_view(), name="item_tag"),
    path(
        "list/store/<slug:slug>/",
        views.StoreItemList.as_view(),
        name="store_list",
    ),
    path(
        "list/remove_param/<slug:param>/",
        views.remove_param,
        name="remove_param",
    ),
    path("detail/<int:pk>/", views.ItemDetail.as_view(), name="item_detail"),
    path(
        "detail/<int:pk>/delete/comment/<int:comment_id>/",
        views.DeleteComment.as_view(),
        name="comment_delete",
    ),
    path(
        "detail/<int:pk>/edit/comment/<int:comment_id>/",
        views.EditComment.as_view(),
        name="comment_edit",
    ),
]

shop/app_settings/urls.py
"""Модуль содержит URL-адреса для работы с настройками сайта."""
from django.urls import path

from app_settings import views

app_name = "app_settings"
urlpatterns = [
    path("admin/dashboard/", views.AdminDashBoardView.as_view(), name="dashboard"),
    path("settings/", views.SettingsView.as_view(), name="settings"),
    path("edit/<int:pk>/", views.SettingsUpdatedView.as_view(), name="settings_edit"),
    path("customer/list/", views.CustomerListView.as_view(), name="customer_list"),
    path(
        "customer/<int:pk>/update/",
        views.CustomerDeleteView.as_view(),
        name="customer_update_status",
    ),
    path("seller/list/", views.SellerListView.as_view(), name="seller_list"),
    path(
        "seller/<int:pk>/update/",
        views.SellerDeleteView.as_view(),
        name="seller_update_status",
    ),
    path("store/list/", views.StoreListView.as_view(), name="store_list"),
    path("product/list/", views.ProductListView.as_view(), name="product_list"),
    path("comments/list/", views.CommentListView.as_view(), name="comments_list"),
    path(
        "comment/<int:pk>/detail/", views.CommentDetail.as_view(), name="comment_detail"
    ),
    path(
        "comment/<int:pk>/update/",
        views.CommentModerate.as_view(),
        name="comment_update",
    ),
    path(
        "comment/<int:pk>/delete/", views.CommentDelete.as_view(), name="comment_delete"
    ),
    path("category/list/", views.CategoryListView.as_view(), name="category_list"),
    path(
        "category/create/", views.CategoryCreateView.as_view(), name="create_category"
    ),
    path(
        "category/<int:pk>/edit/",
        views.CategoryUpdateView.as_view(),
        name="category_edit",
    ),
    path(
        "category/<int:pk>/delete/",
        views.CategoryDeleteView.as_view(),
        name="category_delete",
    ),
    path("tag/list/", views.TagListView.as_view(), name="tag_list"),
    path("tag/create/", views.TagCreateView.as_view(), name="tag_create"),
    path("tag/<int:pk>/edit/", views.TagUpdateView.as_view(), name="tag_edit"),
    path("tag/<int:pk>/delete/", views.TagDeleteView.as_view(), name="tag_delete"),
    path(
        "feature/list/<int:pk>/", views.FeatureListView.as_view(), name="feature_list"
    ),
    path(
        "feature/create/<int:pk>/",
        views.FeatureCreateView.as_view(),
        name="feature_create",
    ),
    path(
        "feature/edit/<int:category_id>/feature/<int:pk>/",
        views.FeatureUpdateView.as_view(),
        name="feature_edit",
    ),
    path(
        "feature/delete/<int:category_id>/feature/<int:pk>/",
        views.FeatureDeleteView.as_view(),
        name="feature_delete",
    ),
    path(
        "feature/value/<int:pk>/create/",
        views.ValueCreateView.as_view(),
        name="value_create",
    ),
    path(
        "feature/delete/<int:category_id>/value/<int:pk>/",
        views.ValueDeleteView.as_view(),
        name="value_delete",
    ),
    path("order/list/", views.OrderListView.as_view(), name="admin_order_list"),
    path(
        "order/<int:pk>/detail/",
        views.OrderDetailView.as_view(),
        name="admin_order_detail",
    ),
]

shop/app_store/urls.py
"""Модуль содержит URL-адреса для работы с магазинами."""
from django.urls import path
from app_store import views

app_name = "app_store"

urlpatterns = [
    path("seller/dashboard/", views.SellerDashBoard.as_view(), name="dashboard"),

    path("store/", views.StoreList.as_view(), name="store_list"),
    path("store/<int:pk>/", views.StoreDetail.as_view(), name="store_detail"),
    path("store/create/", views.StoreCreate.as_view(), name="create_store"),
    path("store/<int:pk>/edit/", views.StoreUpdate.as_view(), name="store_edit"),
    path("store/<int:pk>/category/<slug:slug>/", views.StoreDetail.as_view(), name="category_item"),
    path("store/<int:pk>/sorted/<slug:order_by>/", views.StoreDetail.as_view(), name="item_sorted"),

    path("item/add/<int:pk>/", views.ItemCreate.as_view(), name="add_item"),
    path("item/edit/<int:pk>/", views.ItemUpdate.as_view(), name="edit_item"),
    path("item/delete/<int:pk>/", views.ItemDelete.as_view(), name="delete_item"),

    path("delivery/", views.DeliveryList.as_view(), name="delivery_list"),
    path("delivery/<slug:status>/", views.DeliveryList.as_view(), name="delivery_progress"),
    path("delivery/detail/<int:pk>/", views.DeliveryDetail.as_view(), name="delivery_detail"),
    path("delivery/detail/<int:pk>/edit/", views.DeliveryUpdate.as_view(), name="delivery_edit"),
    path("delivery/item/<int:pk>/edit/", views.OrderItemUpdate.as_view(), name="order_item_edit"),
    path("delivery/sent/<int:pk>/", views.SentPurchase.as_view(), name="sent_purchase"),

    path("comment/list/", views.CommentList.as_view(), name="comment_list"),
    path("comment/<int:pk>/", views.CommentDetail.as_view(), name="comment_detail"),

    path("value/<slug:slug>/item/<int:pk>/del/", views.RemoveValue.as_view(), name="value_del"),
    #
    path("tag/list/", views.TagList.as_view(), name="tag_list"),
    path("tag/add/<int:pk>/", views.AddTag.as_view(), name="add_tag"),
    path("tag/<int:tag_id>/itm/<int:item_id>/del/", views.RemoveTag.as_view(), name="delete_tag"),

    path("image/<int:pk>/del/", views.DeleteImage.as_view(), name="delete_image"),
    path("image/<int:pk>/update/", views.MakeImageAsMain.as_view(), name="make_image_main"),

    path("export_data/<int:pk>/", views.export_data_to_csv, name="export_data"),
    path("import_data/<int:pk>", views.import_data_from_cvs, name="import_data"),
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop import views as shop_views


handler403 = "shop.views.my_permission_denied"
handler404 = "shop.views.my_page_not_found"
handler500 = "shop.views.my_server_error"

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("", shop_views.MainPage.as_view(), name="main"),
    path(
        "accounts/",
        include(("app_user.urls", "app_user"), namespace="app_user"),
    ),
    path(
        "cart/", include(("app_cart.urls", "app_cart"), namespace="app_cart")
    ),
    path(
        "compare/",
        include(("app_compare.urls", "app_compare"), namespace="app_compare"),
    ),
    path(
        "favorite/",
        include(
            ("app_favorite.urls", "app_favorite"), namespace="app_favorite"
        ),
    ),
    path(
        "order/",
        include(("app_order.urls", "app_order"), namespace="app_order"),
    ),
    path(
        "store/",
        include(("app_store.urls", "app_store"), namespace="app_store"),
    ),
    path(
        "item/", include(("app_item.urls", "app_item"), namespace="app_item")
    ),
    path(
        "invoice/",
        include(("app_invoice.urls", "app_invoice"), namespace="app_invoice"),
    ),
    path(
        "settings/",
        include(
            ("app_settings.urls", "app_settings"), namespace="app_settings"
        ),
    ),
    path("__debug__/", include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

shop/app_settings/models.py
"""Модуль содержит модели Настроек сайта."""
from django.core.cache import cache
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.timezone import now


class SingletonModel(models.Model):
    """Модель-синглтон."""

    objects = models.Manager()

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.pk = 1
        super(SingletonModel, self).save(*args, **kwargs)
        self.set_cache()

    @classmethod
    def load(cls):
        """Метод возвращает экземпляр модели из кеша или создает его."""
        if cache.get(cls.__name__) is None:
            obj, created = cls.objects.get_or_create(pk=1)
            if not created:
                obj.set_cache()
        return cache.get(cls.__name__)

    def set_cache(self):
        """Метод устанавливает кеш экземпляр модели."""
        cache.set(self.__class__.__name__, self)


class SiteSettings(SingletonModel):
    """Модель Натсроек сайта."""

    class Delivery(models.TextChoices):
        STANDARD = "обычная доставка"
        EXPRESS = "экспресс доставка"
        ONESELF = "самовывоз"

    STATUS = (
        ("new", "Новый"),
        ("in_progress", "в обработке"),
        ("on_the_way", "доставляется"),
        ("is_ready", "готов к выдаче"),
        ("completed", "доставлен"),
        ("deactivated", "отменен"),
    )
    DELIVERY = (
        ("standard", "обычная доставка"),
        ("express", "экспресс доставка"),
    )
    PAY_TYPE = (
        ("online", "Онлайн картой"),
        ("someone", "Онлайн со случайного чужого счета"),
    )
    express_delivery_price = models.DecimalField(
        decimal_places=2,
        max_digits=9,
        null=True,
        blank=True,
        verbose_name="стоимость экспресс доставки",
        validators=[
            MinValueValidator(0),
        ],
    )
    min_free_delivery = models.DecimalField(
        decimal_places=2,
        max_digits=9,
        null=True,
        blank=True,
        verbose_name="минимальная сумма для бесплатной доставки",
        validators=[
            MinValueValidator(0),
        ],
    )
    delivery_fees = models.DecimalField(
        decimal_places=2,
        max_digits=9,
        null=True,
        blank=True,
        verbose_name="стоимость доставки",
        validators=[
            MinValueValidator(0),
        ],
    )
    cache_detail_view = models.IntegerField(
        verbose_name="время кэширования страницы товара", default=86400
    )
    type_of_delivery = models.CharField(
        max_length=256,
        verbose_name="тип доставки",
        choices=Delivery.choices,
        default="standard",
    )
    type_of_payment = models.CharField(
        max_length=256, verbose_name="тип оплаты", choices=PAY_TYPE, default="online"
    )
    url = models.URLField(verbose_name="Website url", max_length=256)
    title = models.CharField(
        verbose_name="название сайта", max_length=256, default="Megano"
    )
    support_email = models.EmailField(
        default="Support@ninzio.com", verbose_name="электронный ящик"
    )
    phone = models.CharField(
        max_length=256, verbose_name="телефон", default="8-800-200-600"
    )
    address = models.CharField(
        max_length=256,
        verbose_name="адрес",
        default="New York, north Avenue 26/7 0057 ",
    )
    skype = models.CharField(max_length=256, verbose_name="skype", default="techno")
    facebook = models.CharField(
        max_length=256, verbose_name="facebook", default="https://facebook.com/megano"
    )
    twitter = models.CharField(
        max_length=256, verbose_name="twitter", default="https://twitter.com/megano"
    )
    linkedIn = models.CharField(
        max_length=256, verbose_name="linkedIn", default="https://linkedin.com/megano"
    )
    created = models.DateTimeField(auto_now_add=True, verbose_name="дата создания")
    updated = models.DateTimeField(auto_now_add=True, verbose_name="дата обновления")

    class Meta:
        db_table = "app_site_settings"
        verbose_name_plural = "Настройки"

    def __str__(self):
        """Метод для отображения информации об объекте класса SiteSettings."""
        return "Настройки"

    def save(self, *args, **kwargs):
        self.updated = now()
        super().save(*args, **kwargs)

shop/app_settings/forms.py
"""
Модуль содержит формы для работы с настройками сайта.

1. UpdateSettingsForm - форма для обновления настроек сайта,
2. CreateCategoryForm - форма для создания категории,
3. UpdateCategoryForm - форма для редактирования категории,
4. CreateTagForm - форма для создания тегов,
5. CreateFeatureForm -  форма для создания характеристик товар,
6. UpdateFeatureForm - форма для редактирования характеристик товар,
7. CreateValueForm - форма для создания значения характеристики
"""
from django import forms

from app_item import models as item_models
from app_settings import models as settings_models


class UpdateSettingsForm(forms.ModelForm):
    """Форма для обновления настроек сайта."""

    class Meta:
        model = settings_models.SiteSettings
        fields = (
            "express_delivery_price",
            "min_free_delivery",
            "delivery_fees",
            "cache_detail_view",
            "url",
            "title",
            "support_email",
            "phone",
            "skype",
            "address",
            "facebook",
            "twitter",
            "linkedIn",
        )


# CATEGORY FORMS
class CreateCategoryForm(forms.ModelForm):
    """Форма для создания категории товаров."""

    parent_category = forms.ModelChoiceField(
        queryset=item_models.Category.objects.filter(parent_category=None),
        empty_label="--- Выберите значение ---",
        required=False,
    )

    class Meta:
        model = item_models.Category
        fields = (
            "parent_category",
            "title",
            "description",
        )

    def clean_title(self):
        """Функция валидирует сущетвование категории в базе данных."""
        title = self.cleaned_data.get("title")
        if item_models.Category.objects.filter(title=title).exists():
            raise forms.ValidationError("Такая категория уже существует")
        return title


class UpdateCategoryForm(forms.ModelForm):
    """Форма для редактирования категории товаров."""

    my_default_errors = {
        "required": "Это поле является обязательным",
        "invalid": "Категория с таким названием уже существует",
    }

    class Meta:
        model = item_models.Category
        fields = (
            "parent_category",
            "title",
            "description",
        )


# TAG FORMS
class CreateTagForm(forms.ModelForm):
    """Форма для создания тега."""

    class Meta:
        model = item_models.Tag
        fields = ("title",)

    def clean_tag(self):
        """Функция валидирует сущетвование тег в базе данных."""
        tag = self.cleaned_data.get("category").lower()
        if item_models.Tag.objects.filter(title=tag).first().exists():
            raise forms.ValidationError("Такая категория уже существует")
        return tag


# FEATURE & VALUE FORMS
class CreateFeatureForm(forms.ModelForm):
    """Форма для создания характеристики."""

    class Meta:
        model = item_models.Feature
        fields = ("title",)

    def clean_feature(self):
        """Функция валидирует сущетвование характеристики в базе данных."""
        feature = self.cleaned_data.get("title").lower()
        if item_models.Feature.objects.get(title=feature).exists():
            raise forms.ValidationError("Такая характеристика уже существует")
        return feature


class UpdateFeatureForm(forms.ModelForm):
    """Форма для обновления характеристики."""

    class Meta:
        model = item_models.Feature
        fields = ("title",)


class CreateValueForm(forms.ModelForm):
    """Форма для создания значения характеристики."""

    class Meta:
        model = item_models.FeatureValue
        fields = ("value",)

    def clean_value(self):
        """Функция валидирует сущетвование значене характеристики в БД."""

        value = self.cleaned_data.get("value").lower()
        if item_models.FeatureValue.objects.filter(value=value).first():
            raise forms.ValidationError("Такое значение  уже существует")
        else:
            return value

shop/app_settings/templates/app_settings/order/order_detail.html
{% extends 'app_settings/admin/admin_index.html' %}
{% load static  %}
{% load cache %}
{% block title %}

{% endblock %}

{% block content %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">
                    <input class="btn btn_default btn_square" type="button" onclick="history.back(-2); return false;" value="Назад"/>
                    {{ order }}
                </h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item">
                        <a href="{% url 'app_settings:dashboard' %}">главная
                        </a>
                    </li>
                    <li class="breadcrumbs-item">
                         <a href="{% url 'app_settings:admin_order_list' %}">История заказов
                        </a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current">
                        <span>{{ order }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    {% include 'messages/message.html' %}
    <div class="Section">
        <div class="wrap">
            <div class="Section-content">
                <div class="Orders"></div>
                <div class="Order">
                    <div class="Order-infoBlock">
                        <div class="Order-personal">
                            <div class="row">
                                <div class="row-block">
                                    <div class="Order-info Order-info_date">
                                        <div class="Order-infoType">Дата заказа:
                                        </div>
                                        <div class="Order-infoContent">{{ order.created|date:'j F o H:m' }}
                                        </div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">ФИО:
                                        </div>
                                        <div class="Order-infoContent">{{ order.user.get_full_name }}
                                        </div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">Телефон:
                                        </div>
                                        <div class="Order-infoContent" id="phone_formatter">{{ order.telephone }}
                                        </div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">E-mail:
                                        </div>
                                        <div class="Order-infoContent">{{ order.email }}
                                        </div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">Комментарий к заказу
                                        </div>
                                        <div class="Order-infoContent">
                                            {% if order.comment%}
                                            {{ order.comment }}
                                            {% else %} отсутствует
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="row-block">
                                    <div class="Order-info Order-info_delivery">
                                        <div class="Order-infoType">Тип доставки:
                                        </div>
                                        <div class="Order-infoContent
                                                    {% if order.delivery == 'express' %}
                                                    warning-text
                                                    {% endif %}">
                                                    {{ order.get_delivery_display }}
                                        </div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">Город:
                                        </div>
                                        <div class="Order-infoContent">{{ order.city }}
                                        </div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">Адрес:</div>
                                        <div class="Order-infoContent">{{ order.address }}</div>
                                    </div>
                                    <div class="Order-info Order-info_pay">
                                        <div class="Order-infoType">Оплата:</div>
                                        <div class="Order-infoContent">{{ order.get_pay_display }}</div>
                                    </div>
                                    <div class="Order-info Order-info_status">
                                        <div class="Order-infoType">Статус:</div>
                                        <div class="Order-infoContent">{{ order.get_status_display }}

                                        </div>
                                    </div>
                                    {% if order.invoices.first %}
                                    <div class="Order-info Order-info_pay">
                                        <div class="Order-infoType">Квитанция:</div>
                                        <div class="Order-infoContent">{{ order.invoices.first }}

                                        </div>
                                    </div>
                                    {% endif %}
                                    {% if order.error %}
                                    <div class="Order-info Order-info_error">
                                        <div class="Order-infoType">Оплата не прошла:
                                        </div>
                                        <div class="Order-infoContent">{{ order.error }}
                                        </div>
                                    {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="Cart Cart_order">
                            {% for order_item in items %}
                            <div class="Cart-product">
                                <div class="Cart-block Cart-block_row">
                                    <div class="Cart-block Cart-block_pict">
                                        <a class="Cart-pict" href="{% url 'app_item:item_detail' pk=order_item.item.item.pk %}">
                                            <img class="Cart-img" src="{{ order_item.item.item.main_image }}"
                                                 alt="{{ order_item.item.item.title }}"/>
                                        </a>
                                    </div>
                                    <div class="Cart-block Cart-block_info">
                                        <a class="Cart-title" href="{% url 'app_item:item_detail' pk=order_item.item.item.pk %}">
                                            {{ order_item.item.item.title }}
                                        </a>
                                    </div>
                                    <div class="Cart-block Cart-block_price">
                                        <span
                                            class="Cart-price">${{ order_item.item.item.price }}
                                        </span>
                                    </div>

                                    <div class="Cart-block Cart-block_price">
                                        <span class="Cart-price ">{{ order_item.quantity }}шт.
                                        </span>
                                    </div>
                                    <div class="Cart-block Cart-block_price">
                                        <span class="Cart-price">${{ order_item.total }}
                                        </span>

                                    </div>
                                    <div class="Cart-block Cart-block_price">
                                        {% if order.status == 'created' %}
                                        <a class="btn btn_square btn_dark btn_narrow btn_sm" style="margin-left:10px"
                                           href="{% url 'app_store:order_item_edit' order_item.id %}">
                                            редактировать
                                        </a>
                                        {% endif %}
                                        {% if order.status == 'paid' %}
                                        <form method="post"
                                              action="{% url 'app_store:sent_purchase' order_id=order.pk %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="status" value="is_preparing">
                                            <button class="btn btn_square btn_success btn_narrow  btn_sm"> отправить
                                                товар
                                            </button>
                                        </form>
                                        {% endif %}
                                    </div>
                                    <div class="Cart-block Cart-block_price">
                                        {% if order.status == 'created' %}
                                        <a class="btn btn_square btn_danger btn_narrow btn_sm" style="margin-left:10px"
                                           href="#deliveryDeleteModal_{{ order_item.id }}">
                                            x
                                        </a>
                                        {% endif %}
                                        <!--     MODAL FOR CONFIRM DELETE COMMENT    -->
                                        <div id="deliveryDeleteModal_{{ order_item.id }}" class="modal-my">
                                            <div class="modal-dialog-my">
                                                <div class="modal-content-my">
                                                    <div class="modal-header-my">
                                                        <a href="#close" title="Close" class="close-my">×</a>
                                                    </div>
                                                    <div class="modal-body-my">
                                                        <div class="form Payment">
                                                            <div class="form-group">
                                                                <h3>Удалить </h3>{{ order_item }}
                                                            </div>
                                                            <div class="form-group">
                                                                <a href="{% url 'app_store:delivery_edit' order_item.id %}"
                                                                   class="btn btn_square btn_danger btn_narrow">удалить&#8195;x</a>
                                                                <a href="." title="Close"
                                                                   class="btn btn_square btn_dark btn_narrow">отмена</a>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer-my"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--     MODAL FOR CONFIRM DELETE COMMENT    -->
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                         <div class="Cart-total">
                             <div class="Cart-block Cart-block_total">
                                 <strong class="Cart-title">Итого:
                                     <span class="Cart-price">${{ total|floatformat:'2' }}</span>
                                 </strong>
                             </div>
                         </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}