shop/app_cart/urls.py
"""Модуль содержит URL-адреса для работы с корзиной."""

from django.urls import path
from app_cart import views

app_name = "app_cart"

urlpatterns = [
    path("<int:pk>/detail/", views.CartDetail.as_view(), name="cart"),
    path("cart_create/", views.CreateCart.as_view(), name="cart_create"),
    path("add/<int:pk>/", views.AddItemToCart.as_view(), name="add_cart"),
    path(
        "update/<int:pk>/item/<int:item_id>/",
        views.UpdateCountItem.as_view(),
        name="update",
    ),
    path(
        "remove/<int:pk>/",
        views.RemoveItemFromCart.as_view(),
        name="remove_cart",
    ),
]

shop/app_order/urls.py
"""Модуль содержит URL-адреса для работы с заказами."""
from django.urls import path

from app_order import views


app_name = "app_order"

urlpatterns = [
    path("order_create/", views.OrderCreate.as_view(), name="order_create"),
    path("order_list/", views.OrderList.as_view(), name="order_list"),
    path(
        "order_list/<slug:status>/",
        views.OrderList.as_view(),
        name="order_progress",
    ),
    path(
        "order_detail/<int:pk>/",
        views.OrderDetail.as_view(),
        name="order_detail",
    ),
    path(
        "order_update/<int:pk>/update/",
        views.OrderUpdatePayWay.as_view(),
        name="order_update",
    ),
    path(
        "order_detail/<int:pk>/confirm/",
        views.ConfirmReceiptPurchase.as_view(),
        name="order_confirm",
    ),
    path(
        "order_list/<int:pk>/cancel/",
        views.OrderCancel.as_view(),
        name="order_cancel",
    ),
    path(
        "progress_payment/<int:pk>/",
        views.PaymentView.as_view(),
        name="progress_payment",
    ),
    path("pay_order/", views.pay_order, name="pay_order"),
    path(
        "get_status_payment/<int:order_id>/<task_id>/",
        views.get_status_payment,
        name="get_status_payment",
    ),
    path(
        "success_pay/<int:order_id>/",
        views.SuccessPaid.as_view(),
        name="success_pay",
    ),
    path(
        "failed_pay/<int:order_id>/",
        views.FailedPaid.as_view(),
        name="failed_pay",
    ),
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop import views as shop_views


handler403 = "shop.views.my_permission_denied"
handler404 = "shop.views.my_page_not_found"
handler500 = "shop.views.my_server_error"

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("", shop_views.MainPage.as_view(), name="main"),
    path(
        "accounts/",
        include(("app_user.urls", "app_user"), namespace="app_user"),
    ),
    path(
        "cart/", include(("app_cart.urls", "app_cart"), namespace="app_cart")
    ),
    path(
        "compare/",
        include(("app_compare.urls", "app_compare"), namespace="app_compare"),
    ),
    path(
        "favorite/",
        include(
            ("app_favorite.urls", "app_favorite"), namespace="app_favorite"
        ),
    ),
    path(
        "order/",
        include(("app_order.urls", "app_order"), namespace="app_order"),
    ),
    path(
        "store/",
        include(("app_store.urls", "app_store"), namespace="app_store"),
    ),
    path(
        "item/", include(("app_item.urls", "app_item"), namespace="app_item")
    ),
    path(
        "invoice/",
        include(("app_invoice.urls", "app_invoice"), namespace="app_invoice"),
    ),
    path(
        "settings/",
        include(
            ("app_settings.urls", "app_settings"), namespace="app_settings"
        ),
    ),
    path("__debug__/", include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

shop/templates/footer/footer.html
{% load cache %}
{% cache 60 footer %}
<footer class="Footer">
    <div class="wrap">
        <div class="row Footer-main">
            <div class="row-block">
                <a class="logo Footer-logo" href="index.html">
                    <img class="logo-image" src="/assets/img/logo_footer.png" alt="logo_footer.png"/>
                </a>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincid unt ut
                    laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad
                </p>
                <ul class="menu menu_img menu_smallImg Footer-menuSoc">
                    <li class="menu-item">
                        <a class="menu-link" href="{{ site_settings.facebook }}">
                            <img src="/assets/img/icons/socialFooter/fb.svg" alt="fb.svg"/>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{{ site_settings.twitter }}">
                            <img src="/assets/img/icons/socialFooter/tw.svg" alt="tw.svg"/>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{{ site_settings.linkedIn }}">
                            <img src="/assets/img/icons/socialFooter/in.svg" alt="in.svg"/>
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">
                            <img src="/assets/img/icons/socialFooter/pt.svg" alt="pt.svg"/>
                        </a>
                    </li>
                    <li class="menu-item"><a class="menu-link" href="{{ site_settings.support_email }}">
                        <img src="/assets/img/icons/socialFooter/mail.svg" alt="mail.svg"/>
                    </a>
                    </li>
                </ul>
            </div>
            <div class="row-block">
                <strong class="Footer-title">Useful Links
                </strong>
                <ul class="menu menu_vt Footer-menu">
                    <li class="menu-item">
                        <a class="menu-link" href="#">Checkout
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% if cart_dict.cart %}
                       {% url 'app_cart:cart' pk=cart_dict.cart.pk  %}
                       {% else %}
                       {% url 'app_cart:cart_create' %}
                       {% endif %}">Корзина
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">Доставка
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'app_order:order_list' %}">Заказы
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">Terms
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">Conditions
                        </a>
                    </li>
                </ul>
            </div>
            <div class="row-block">
                <strong class="Footer-title">My Account
                </strong>
                <ul class="menu menu_vt Footer-menu">
                    <li class="menu-item">
                        <a class="menu-link" href="#">Accessories
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">Bags
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">Cameras
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">Clothings
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">Electronics
                        </a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="#">Fashion
                        </a>
                    </li>
                </ul>
            </div>
            <div class="row-block">
                <strong class="Footer-title">Contacts
                </strong>
                <p>Phone: {{ site_settings.phone }}<br>
                    Email: {{ site_settings.support_email }}<br>
                    Skype: {{ site_settings.skype }}<br>
                    Address: {{ site_settings.address }}<br>

                </p>
            </div>
        </div>
    </div>
    <div class="Footer-copy">
        <div class="wrap">
            <div class="row row_space">
                <div class="row-block">© Copyright&#32;
                    <a href="#">Megano Store.</a>&#32;All rights reserved.
                </div>
                <div class="row-block"><span>Accepted Payments</span>
                    <div class="Footer-payments">
                        <div><img src="/assets/img/payments/visa.png" alt="visa.png"/>
                        </div>
                        <div><img src="/assets/img/payments/mastercard.png" alt="mastercard.png"/>
                        </div>
                        <div><img src="/assets/img/payments/paypal.png" alt="paypal.png"/>
                        </div>
                        <div><img src="/assets/img/payments/american.png" alt="american.png"/>
                        </div>
                        <div><img src="/assets/img/payments/electron.png" alt="electron.png"/>
                        </div>
                        <div><img src="/assets/img/payments/maestro.png" alt="maestro.png"/>
                        </div>
                        <div><img src="/assets/img/payments/delta.png" alt="delta.png"/>
                        </div>
                        <div><img src="/assets/img/payments/e.png" alt="e.png"/>
                        </div>
                        <div><img src="/assets/img/payments/dk.png" alt="dk.png"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
{% endcache %}