shop/app_store/urls.py
"""Модуль содержит URL-адреса для работы с магазинами."""
from django.urls import path
from app_store import views

app_name = "app_store"

urlpatterns = [
    path("seller/dashboard/", views.SellerDashBoard.as_view(), name="dashboard"),

    path("store/", views.StoreList.as_view(), name="store_list"),
    path("store/<int:pk>/", views.StoreDetail.as_view(), name="store_detail"),
    path("store/create/", views.StoreCreate.as_view(), name="create_store"),
    path("store/<int:pk>/edit/", views.StoreUpdate.as_view(), name="store_edit"),
    path("store/<int:pk>/category/<slug:slug>/", views.StoreDetail.as_view(), name="category_item"),
    path("store/<int:pk>/sorted/<slug:order_by>/", views.StoreDetail.as_view(), name="item_sorted"),

    path("item/add/<int:pk>/", views.ItemCreate.as_view(), name="add_item"),
    path("item/edit/<int:pk>/", views.ItemUpdate.as_view(), name="edit_item"),
    path("item/delete/<int:pk>/", views.ItemDelete.as_view(), name="delete_item"),

    path("delivery/", views.DeliveryList.as_view(), name="delivery_list"),
    path("delivery/<slug:status>/", views.DeliveryList.as_view(), name="delivery_progress"),
    path("delivery/detail/<int:pk>/", views.DeliveryDetail.as_view(), name="delivery_detail"),
    path("delivery/detail/<int:pk>/edit/", views.DeliveryUpdate.as_view(), name="delivery_edit"),
    path("delivery/item/<int:pk>/edit/", views.OrderItemUpdate.as_view(), name="order_item_edit"),
    path("delivery/sent/<int:pk>/", views.SentPurchase.as_view(), name="sent_purchase"),

    path("comment/list/", views.CommentList.as_view(), name="comment_list"),
    path("comment/<int:pk>/", views.CommentDetail.as_view(), name="comment_detail"),

    path("value/<slug:slug>/item/<int:pk>/del/", views.RemoveValue.as_view(), name="value_del"),
    #
    path("tag/list/", views.TagList.as_view(), name="tag_list"),
    path("tag/add/<int:pk>/", views.AddTag.as_view(), name="add_tag"),
    path("tag/<int:tag_id>/itm/<int:item_id>/del/", views.RemoveTag.as_view(), name="delete_tag"),

    path("image/<int:pk>/del/", views.DeleteImage.as_view(), name="delete_image"),
    path("image/<int:pk>/update/", views.MakeImageAsMain.as_view(), name="make_image_main"),

    path("export_data/<int:pk>/", views.export_data_to_csv, name="export_data"),
    path("import_data/<int:pk>", views.import_data_from_cvs, name="import_data"),
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop import views as shop_views


handler403 = "shop.views.my_permission_denied"
handler404 = "shop.views.my_page_not_found"
handler500 = "shop.views.my_server_error"

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("", shop_views.MainPage.as_view(), name="main"),
    path(
        "accounts/",
        include(("app_user.urls", "app_user"), namespace="app_user"),
    ),
    path(
        "cart/", include(("app_cart.urls", "app_cart"), namespace="app_cart")
    ),
    path(
        "compare/",
        include(("app_compare.urls", "app_compare"), namespace="app_compare"),
    ),
    path(
        "favorite/",
        include(
            ("app_favorite.urls", "app_favorite"), namespace="app_favorite"
        ),
    ),
    path(
        "order/",
        include(("app_order.urls", "app_order"), namespace="app_order"),
    ),
    path(
        "store/",
        include(("app_store.urls", "app_store"), namespace="app_store"),
    ),
    path(
        "item/", include(("app_item.urls", "app_item"), namespace="app_item")
    ),
    path(
        "invoice/",
        include(("app_invoice.urls", "app_invoice"), namespace="app_invoice"),
    ),
    path(
        "settings/",
        include(
            ("app_settings.urls", "app_settings"), namespace="app_settings"
        ),
    ),
    path("__debug__/", include("debug_toolbar.urls")),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

shop/app_store/models.py
"""Модуль содержит модель Магазина."""
import os

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse

from app_store.managers.app_store_managers import StoreIsActiveManager
from utils.my_utils import slugify_for_cyrillic_text


class Store(models.Model):
    """Модель магазина."""

    DEFAULT_IMAGE = "default_images/store.png"

    title = models.CharField(
        max_length=200,
        db_index=True,
        verbose_name="название магазина"
    )
    slug = models.SlugField(
        max_length=100,
        db_index=True,
        allow_unicode=False,
        verbose_name="slug"
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="store",
        verbose_name="собственник",
    )
    discount = models.SmallIntegerField(
        default=0,
        verbose_name="скидка",
        validators=[MaxValueValidator(99), MinValueValidator(0)],
    )
    min_for_discount = models.IntegerField(
        default=0,
        verbose_name="минимальная сумма для бесплатной доставки",
        validators=[MinValueValidator(0)],
    )
    description = models.TextField(
        default="",
        blank=True,
        verbose_name="Описание магазина"
    )
    logo = models.ImageField(
        upload_to="store/logo/",
        default="default_images/default_store.jpg",
        blank=True
    )
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name="дата создания"
    )
    updated = models.DateTimeField(
        auto_now_add=True,
        verbose_name="дата обновления"
    )

    objects = models.Manager()
    active_stores = StoreIsActiveManager()

    class Meta:
        db_table = "app_store"
        ordering = ["title", "created"]
        verbose_name = "магазин"
        verbose_name_plural = "магазины"

    def __str__(self):
        """Метод для отображения информации об объекте класса Store."""
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_for_cyrillic_text(self.title)
        super(Store, self).save(*args, **kwargs)

    @property
    def get_logo(self):
        """
        Метод возвращает URL-изображения категории.

        Возвращает URL-изображения
        или дефолтное изображение.
        """
        if self.logo:
            return os.path.join(settings.MEDIA_URL, self.logo.url)
        else:
            return os.path.join(settings.MEDIA_URL, self.DEFAULT_IMAGE)

    def get_absolute_url(self):
        """Метод возвращает абсолютный путь до магазина."""
        return reverse("app_item:store_list", kwargs={"slug": self.slug})

    @property
    def store_items(self):
        """Метод возвращает все товары магазина."""
        return self.items.all()

    @property
    def all_orders(self):
        """Метод возвращает все заказы магазина."""
        return self.orders.count()

    @property
    def cash(self):
        """Метод возвращает сумму всех заказов."""
        return (
            self.orders.filter(order_items__item__item__store=self.id)
            .aggregate(total=Sum("order_items__item__total"))
            .get("total")
        )

    @property
    def paid_item(self):
        """Метод возвращает кол-во всех заказов."""
        return (
            self.orders.filter(order_items__item__item__store=self.id)
            .aggregate(total=Sum("order_items__quantity"))
            .get("total")
        )

shop/app_store/views.py
"""
Модуль содержит классы-предстывления для работы с магазинами.

    1. SellerDashBoardView - для отображения панели продавца,
    классы-представления для работы с магазином:
        2. StoreList - для отображения списка магазинов,
        3. StoreDetail - для отображения одного магазина,
        4. StoreCreate - для отображения создания магазина,
        5. StoreUpdate - для отображения редакирования магазина,
    классы-представления для работы с товарами:
        6. ItemCreate - для создания товара,
        7. ItemUpdate - для редакирования товара,
        8. ItemDelete - для де(активации) товара,
    классы-представления для работы с тегами:
        9. TagList - для отображения списка тегов,
        10. AddTag - для добавления тега в карточку товара,
        11. RemoveTag - для удаления тега из карточки товара,
    классы-представления для работы с тегами:
        12. RemoveValue - для удаления значение характеристики товара,
    классы-представления для работы с изображением:
        13. DeleteImage - для удаления изображения из карточки товара,
        14. MakeImageAsMain - для выбора изображения главным,
    классы-представления для работы с заказами:
        15. DeliveryList - для отображения списка заказов,
        16. DeliveryDetail - для отображения одного заказа,
        17. DeliveryUpdate - для редактирования заказа,
        18. OrderItemUpdate - для редактирования товаров в заказе,
        19. SentPurchase - для отправки заказа,
    классы-представления для работы с комментариями:
        20. CommentList - для отображения списка комментариев.
        21. CommentDetail - для отображения одного комментария.
    функции для работы с фикстурами:
        22. export_data_to_csv - для экспорта данных из БД в CVS формат,
        23. import_data_from_cvs - для импорта данных в БД в CVS формат,
        24. handle_uploaded_file - для создания файла с фикстурами.
"""

import csv
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db import transaction
from django.db.models import Sum, Q
from django.http import Http404, HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.views import generic
from django.http import HttpResponse

# models
from app_item import models as itm
from app_order import models as orm
from app_store import models as stm

# services
from app_item.services import comment_services as com_src
from app_order.services import order_services as ord_src
from app_item.services import item_services as itm_src
from app_store.services import store_services as str_src

# forms
from app_order import forms as ord_frm
from app_store import forms as str_frm

# other
from utils.my_utils import MixinPaginator, SellerOnlyMixin
from app_order import tasks


class SellerDashBoard(SellerOnlyMixin, generic.TemplateView):
    """Класс-представление для отображения главной страницы продавца."""

    template_name = "app_store/dashboard.html"

    def get(self, request, *args, **kwargs):
        """GET-функция для рендеренга главной страницы продавца."""
        context = self.get_context_data(**kwargs)
        context["comments"] = com_src.CommentHandler.seller_stores_comments(
            request.user
        )
        context["orders"] = ord_src.SellerOrderHAndler.get_seller_order_list(
            request.user.id
        ).count()
        context["stores"] = str_src.StoreHandler.get_all_story_by_owner(
            request.user
        ).count()

        return self.render_to_response(context)


# STORE VIEWS #
class StoreList(SellerOnlyMixin, generic.ListView):
    """Класс-представление для отображения списка магазинов продавца."""

    model = stm.Store
    template_name = "app_store/store/store_list.html"
    context_object_name = "stores"

    def get_queryset(self):
        """Функция возвращает queryset магазинов."""
        owner = self.request.user
        queryset = str_src.StoreHandler.get_all_story_by_owner(owner)
        return queryset


class StoreDetail(UserPassesTestMixin, generic.DetailView, MixinPaginator):
    """Класс-представление для отображения одного магазина."""

    model = stm.Store
    template_name = "app_store/store/store_detail.html"
    context_object_name = "store"
    paginate_by = 7

    def test_func(self):
        """Функция проверяет прова на просмотр магазина."""
        user = self.request.user
        store = self.get_object()
        return True if user == store.owner else False

    def get(self, request, *args, category=None, **kwargs) -> HttpResponse:
        """
        Функция возвращает экземпляр магазина.

        :param request: HttpRequest
        :param category: категория товара
        :param kwargs: 'order_by' параметр сортировки товаров
        :return: response
        """
        super().get(request, *args, **kwargs)
        context = self.get_context_data(object=self.object)
        store = self.get_object()
        all_items = store.items.all()

        try:
            category_slug = kwargs["slug"]
            category = itm_src.CategoryHandler.get_categories(category_slug)
            items = all_items.filter(category=category)
        except (ObjectDoesNotExist, KeyError):
            items = all_items
        if request.GET.get("q"):
            query = str(request.GET.get("q"))  # [:-1]
            title = query.title()
            lower = query.lower()
            items = (
                all_items.select_related("category", "store")
                .prefetch_related("tag", "views", "images", "feature_value")
                .filter(
                    Q(title__icontains=title) |
                    Q(title__icontains=lower)
                )
                .distinct()
            )
        if request.GET.get("order_by", None):
            order_by = request.GET.get("order_by")
            items = str_src.StoreHandler.ordering_store_items(
                queryset=items, order_by=order_by
            )
            context["message"] = str_src.StoreHandler.ordering_message(
                order_by=order_by
            )
        categories = itm_src.CategoryHandler.get_categories_in_items_set(
            all_items
        )
        object_list = MixinPaginator(
            items, self.request, self.paginate_by
        ).my_paginator()
        total_profit = str_src.StoreHandler.total_profit_store(store)
        context["categories"] = categories
        context["object_list"] = object_list
        context["total_profit"] = total_profit

        return self.render_to_response(context)


class StoreCreate(SellerOnlyMixin, generic.CreateView):
    """Класс-представление для создания магазина."""

    model = stm.Store
    template_name = "app_store/store/create_store.html"
    form_class = str_frm.CreateStoreForm

    def form_valid(self, form):
        """Функция валидации формы для создания магазина."""
        store = form.save()
        store.is_active = True
        store.owner = self.request.user
        store.save()
        return redirect("app_store:store_detail", store.pk)

    def form_invalid(self, form):
        """Функция инвалидации формы для создания магазина."""
        form = str_frm.CreateStoreForm(self.request.POST, self.request.FILES)
        messages.add_message(
            self.request,
            messages.ERROR,
            "Ошибка. Магазин не создан. Повторите попытку.",
        )
        return super().form_invalid(form)


class StoreUpdate(UserPassesTestMixin, generic.UpdateView):
    """Класс-представление для обновления магазина."""

    model = stm.Store
    template_name = "app_store/store/store_edit.html"
    context_object_name = "store"
    form_class = str_frm.UpdateStoreForm
    message = "Данные магазтина обновлены"

    def test_func(self):
        """Функция проверяет прова на редактирования магазина."""
        user = self.request.user
        store = self.get_object()
        return True if user == store.owner else False

    def get_success_url(self):
        """Функция возвращает url-адрес успешного выполнения."""
        store = self.get_object()
        return redirect("app_store:store_edit", store.pk)

    def form_valid(self, form):
        """Функция валидации формы для редактирования магазина."""
        form.save()
        messages.add_message(self.request, messages.SUCCESS, self.message)
        return self.get_success_url()

    def form_invalid(self, form):
        """Функция инвалидации формы для редактирования магазина."""
        messages.add_message(self.request, messages.ERROR, self.message)
        return super(StoreUpdate, self).form_invalid(form)


# ITEM VIEWS #
class ItemCreate(SellerOnlyMixin, generic.CreateView):
    """Класс-представление для создания и добавления товара в магазин."""

    model = stm.Store
    template_name = "app_store/item/add_item.html"
    form_class = str_frm.AddItemImageForm
    second_form_class = str_frm.TagFormSet

    def get_context_data(self, **kwargs):
        """Функция возвращает context-словарь с данными для создания товара."""
        formset_tag = str_frm.TagFormSet(queryset=itm.Tag.objects.none())
        formset_image = str_frm.ImageFormSet(
            queryset=itm.Image.objects.none()
        )
        context = {
            "tag_formset": formset_tag,
            "image_formset": formset_image,
            "form": self.form_class,
            "store": self.get_object(),
            "colors": itm_src.ItemHandler.colors,
            "category_set": itm.Category.objects.all(),
        }
        return context

    def form_valid(self, form):
        """Функция валидации формы для создания товара."""
        with transaction.atomic():
            item = form.save(commit=False)
            item.is_active = True
            item.save()
            images = self.request.FILES.getlist("image")
            tag_list = form.cleaned_data.get("tag")

shop/app_store/templates/app_store/store/create_store.html
{% extends 'app_store/seller_index.html' %}
{% load static %}
{% load cache %}

{% block title %}Создать магазин{% endblock %}

{% block content %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">Создать магазин
                </h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item">
                        <a href="{% url 'app_store:store_list' %}">мои магазины
                        </a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current">
                        <span>Создать новый магазин
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                {% include "app_store/sidebar_seller.html" %}
            </div>
            <div class="Section-content">
                <div class="Profile">
                    <form class="form Profile-form" action="." method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="row-block">
                                <!--    OWNER FIELD  -->
                                <div class="form-group">
                                    <label class="form-label" for="owner">собственник </label>
                                    <label class="form-input" for="owner">{{ request.user.get_full_name }}</label>
                                    <input class="form-input" id="owner" name="owner" type="hidden"
                                            value="{{ request.user.id }}"/>
                                    {% if form.errors.owner %}
                                    <div class="form-error">{{ form.errors.owner }}
                                    </div>
                                    {% endif %}
                                </div>
                                <!--    OWNER FIELD  -->

                                <!--    TITLE FIELD  -->
                                <div class="form-group">
                                    <label class="form-label" for="title">название магазина</label>
                                    <input class="form-input" id="title" name="title" type="text"/>
                                    {% if form.errors.title %}
                                    <div class="form-error">{{ form.errors.title }}
                                    </div>
                                    {% endif %}
                                </div>
                                <!--    TITLE FIELD  -->

                                <!--    DELIVERY FEES FIELD  -->
                                <div class="form-group">
                                    <label class="form-label" for="discount">скидка</label>
                                    <input class="form-input" id="discount" name="discount" type="number" value="0"/>
                                    {% if form.errors.discount %}
                                    <div class="form-error">{{ form.errors.discount }}
                                    </div>
                                    {% endif %}
                                </div>
                                <!--    DELIVERY FEES FIELD   -->
                                <!--    MINIMUM FREE DELIVERY  FIELD  -->
                                <div class="form-group">
                                    <label class="form-label" for="min_for_discount">минимальная сумма для скидки
                                    </label>
                                    <input class="form-input" id="min_for_discount" name="min_for_discount"
                                           type="number" value="0"/>
                                    {% if form.errors.min_for_discount %}
                                    <div class="form-error">{{ form.errors.min_for_discount }}
                                    </div>
                                    {% endif %}
                                </div>
                                <!--    MINIMUM FREE DELIVERY  FIELD  -->



                            </div>
                            <div class="row-block">
                                <!--    LOGO FIELD  -->
                                <div class="form-group">
                                    <label class="form-label" for="logo">Аватар
                                    </label>
                                    <div class="Profile-avatar">
                                        <div class="Profile-img">
                                            {% if user.profile.avatar %}
                                            <img src="/media/default_images/store.png" alt="логотип магазина"/>
                                            {% endif %}
                                        </div>
                                        {% if form.errors.avatar %}
                                        <div class="form-error">{{ form.errors.avatar }}</div>
                                        {% endif %}
                                        <label class="Profile-fileLabel" for="logo">Выберите аватар
                                        </label>
                                        <input class="Profile-file form-input" id="logo" name="logo"
                                               data-validate="onlyImgAvatar" type="file"/>
                                    </div>
                                </div>
                                <!--    LOGO FIELD  -->
                                    <!--    TITLE DESCRIPTION  -->
                                <div class="form-group">
                                    <label class="form-label" for="description">описание</label>
                                    <textarea class="form-input" id="description" name="description"
                                              placeholder="Описание"></textarea>
                                    {% if form.errors.description %}
                                    <div class="form-error">{{ form.errors.description }}
                                    </div>
                                    {% endif %}
                                </div>
                                <!--    TITLE DESCRIPTION  -->

                                <div class="form-group">
                                    <div class="Profile-btn">
                                        <button class="btn btn_success btn_square btn_full" type="submit">Сохранить
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

shop/app_store/templates/app_store/store/store_list.html
{% extends 'app_store/seller_index.html' %}
{% load static %}
{% load cache %}

{% block title %}Магазин{% endblock %}

{% block content %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">Список моих магазинов </h1>
                {% block breadcrumbs %}
                 <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item">
                        <a href="{% url 'app_store:dashboard' %}">главная стариница
                        </a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current">
                        <span>мои магазины
                        </span>
                    </li>
                </ul>
                {% endblock %}
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection">
                     {% include "app_store/sidebar_seller.html" %}
                </div>
            </div>
            <div class="Section-content">
                <div class="Orders">
                    {% for store in stores %}
                    <div class="Order Order_anons">
                        <a class="Order-personal" href="{% url 'app_store:store_detail' store.pk %}">
                            <div class="row">
                                <div class="row-block">
                                    <div class="Order-info Order-info_delivery">
                                        <img src="{{ store.get_logo }}" width="100" height="100">
                                    </div>
                                </div>
                                <div class="row-block">
                                    <div class="Order-info Order-info_delivery">
                                        <div class="Order-title">
                                            <span class="Order-numberOrder">{{store.title}}
                                            </span>
                                        </div>
                                    </div>
                                    <div class="Order-info Order-info_pay">
                                        <div class="Order-infoType">
                                            Описание:
                                        </div>
                                        <div class="Order-infoContent">
                                            {{ store.description|truncatechars:54 }}
                                        </div>
                                    </div>
                                    <div class="Order-info Order-info_delivery">
                                        <div class="Order-infoType">Позиций товаров:
                                        </div>
                                        <div class="Order-infoContent">{{ store.items.count }}
                                        </div>
                                    </div>
                                    <div class="Order-info Order-info_status">
                                        <div class="Order-infoType">Статус:
                                        </div>
                                        <div class="Order-infoContent">
                                            {% if store.is_active %}
                                            <span class="seller_label">активный</span>
                                            {% else %}
                                            <span class="rest_label">не активный</span>
                                            {% endif %}

                                        </div>
                                    </div>

                                </div>
                            </div>
                        </a>
                    </div>
                    {% empty %}

                    <div class="Order ">
                        <div class="Order-personal">
                            <div class="row">
                                <div class="Section-title">
                                    у вас нет магазинов
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <a href="{% url 'app_store:create_store' %}"
                                   class="btn btn_primary">+ создать новый магазин
                                </a>
                            </div>
                        </div>
                    </div>

                        {% endfor %}
                </div>
                <!--       PAGINATION         -->
                {% include "pagination/pagination.html" %}
                <!--       PAGINATION         -->
            </div>
        </div>
    </div>
</div>
{% endblock %}